name = "GeneralizedMorseWavelets"
uuid = "b8d14031-e142-472f-b25f-bd9018bb5b90"
authors = ["Gabriel Destouet <gabriel.destouet@protonmail.com>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ChainRulesCore = "1"
SpecialFunctions = "2"
julia = "1.6"
